### ISSUE TITLE
Fail to add contacts (OJSXC, Nextcloud, Prosody, xmpp-cloud-auth)

### ISSUE THREAD

**Issue by mejo-** [jsxc/xmpp-cloud-auth#9] opened 2017-04-07 08:28 UTC
Hi,

I'm following up on the latest problem I described in https://github.com/jsxc/xmpp-cloud-auth/issues/6#issuecomment-292239904.

After setting up Prosody with xmpp-cloud-auth and switching from the internal XMPP server to the external Prosody in OJSXC, the contact list of OJSXC is empty and I fail to add new contacts to it.

When trying to add a new contact, the auto-completion works: after inserting at least one character, I get a list of all contacts that match it for selection. So reading in the list of contacts seems to work. But when I submit by pressing 'Hinzufügen' ('add contact'), nothing happens. The formular closes, but no contact is actually added to the contact list.

The relevant logs are attached below.

`prosody.log`:

```
Apr 07 10:19:29 http.server	debug	Firing event: POST cloud.example.org/http-bind/
Apr 07 10:19:29 mod_bosh	debug	Handling new request table: 0x561dda3f4f40: <body rid='1264566821' xmlns='http://jabber.org/protocol/httpbind' sid='d71eb9fd-dbd1-4a8f-8b99-655630cbbaca'><iq type='set' xmlns='jabber:client' id='d1ef7c12-716d-443a-8b65-72ae777d7a6d:sendIQ'><query xmlns='jabber:iq:roster'><item jid='test_user@cloud.example.org' name='test_user'/></query></iq><presence to='test_user@cloud.example.org' type='subscribe' xmlns='jabber:client'/></body>
----------
Apr 07 10:19:29 mod_bosh	debug	BOSH body open (sid: d71eb9fd-dbd1-4a8f-8b99-655630cbbaca)
Apr 07 10:19:29 mod_bosh	debug	BOSH stanza received: <iq id='d1ef7c12-716d-443a-8b65-72ae777d7a6d:sendIQ' type='set'>

Apr 07 10:19:29 boshd71eb9fd-dbd1-4a8f-8b99-655630cbbaca	debug	Received[c2s]: <iq id='d1ef7c12-716d-443a-8b65-72ae777d7a6d:sendIQ' type='set'>
Apr 07 10:19:29 cloud.example.org:auth_external	debug	Sent 32 bytes
Apr 07 10:19:29 rostermanager	debug	not saving roster for admin@cloud.example.org: the user doesn't exist
Apr 07 10:19:29 mod_bosh	debug	BOSH stanza received: <presence to='test_user@cloud.example.org' type='subscribe'>

Apr 07 10:19:29 boshd71eb9fd-dbd1-4a8f-8b99-655630cbbaca	debug	Received[c2s]: <presence to='test_user@cloud.example.org' type='subscribe'>
Apr 07 10:19:29 cloud.example.org:presence	debug	outbound presence subscribe from admin@cloud.example.org for test_user@cloud.example.org
Apr 07 10:19:29 rostermanager	debug	load_roster: asked for: admin@cloud.example.org
Apr 07 10:19:29 cloud.example.org:presence	debug	inbound presence subscribe from admin@cloud.example.org for test_user@cloud.example.org
Apr 07 10:19:29 rostermanager	debug	load_roster: asked for: test_user@cloud.example.org
Apr 07 10:19:29 rostermanager	debug	load_roster: loading for offline user: test_user@cloud.example.org
Apr 07 10:19:29 rostermanager	debug	load_roster: asked for: test_user@cloud.example.org
Apr 07 10:19:29 rostermanager	debug	load_roster: loading for offline user: test_user@cloud.example.org
Apr 07 10:19:29 cloud.example.org:auth_external	debug	Sent 37 bytes
Apr 07 10:19:29 rostermanager	debug	not saving roster for test_user@cloud.example.org: the user doesn't exist
Apr 07 10:19:29 mod_bosh	debug	We have an open request, so sending on that

Apr 07 10:19:29 mod_bosh	debug	Request destroyed: table: 0x561dda25f1c0
Apr 07 10:19:29 mod_bosh	debug	Session d71eb9fd-dbd1-4a8f-8b99-655630cbbaca has 1 out of 1 requests open
Apr 07 10:19:29 mod_bosh	debug	and there are 0 things in the send_buffer:
Apr 07 10:19:29 mod_bosh	debug	Have nothing to say, so leaving request unanswered for now
```

And `extauth.log`:

```
2017-04-07 10:19:29,027 INFO: Receive operation isuser
2017-04-07 10:19:29,027 INFO: Receive operation isuser
```

Apparently Prosody doesn't know about the users even though the auth_external_command successfully verifies that the user exists:

```
Apr 07 10:19:29 rostermanager	debug	not saving roster for admin@cloud.example.org: the user doesn't exist
[...]
Apr 07 10:19:29 rostermanager	debug	not saving roster for test_user@cloud.example.org: the user doesn't exist
```

Kind regards,
 jonas

**Comment by sualko** [comment] 2017-04-07 08:33
duplicate of #8

**Closed by sualko** 2017-04-07 08:33 UTC

**Comment by mejo-** [comment] 2017-04-07 08:38
Upps, sorry for opening a duplicate.
